### PR TITLE
Create token.txt

### PR DESCRIPTION
**Pull request by mdevashish**

### CODE REVIEW

**Comment by plasmatic1** [comment]
bruh r u fuckin high dont do that you know that everyone can now log in as your account now right @mdevashish

**Comment by ehhthing** [comment]
Committing your Discord tokens to GitHub is a huge no-no, I'd recommend that you remove the token *and* invalidate it by generating a new one.

**Comment by mdevashish** [comment]
Bro can I deploy it on heroku??

**Comment by ehhthing** [comment]
To deploy to heroku, you can use environment variables and access them in node with https://nodejs.org/api/process.html#process_process_env

**Pull request closed without merging**
